# Generated by Django 5.2 on 2025-06-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('pname', models.CharField(max_length=50)),
                ('pin', models.CharField(max_length=50)),
                ('branch_name', models.CharField(default=None, max_length=50)),
                ('image', models.CharField(max_length=50)),
                ('branch_id', models.IntegerField(default=0)),
                ('folder_url', models.CharField(max_length=20)),
                ('id_user', models.IntegerField(default=0)),
            ],
        ),
    ]
