# Generated by Django 5.2 on 2025-06-21 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='fname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='userdata',
            old_name='image',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='userdata',
            old_name='lname',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='userdata',
            old_name='pname',
            new_name='patronymic',
        ),
        migrations.RenameField(
            model_name='userdata',
            old_name='id_user',
            new_name='uid',
        ),
    ]
