# Generated by Django 5.2 on 2025-06-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_userdata_branch_id_alter_userdata_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='photo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
