# Generated by Django 5.2 on 2025-07-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_userdata_photo'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userdata',
            index=models.Index(fields=['uid', 'branch_id'], name='main_userda_uid_d777cf_idx'),
        ),
    ]
