# Generated by Django 5.2 on 2025-07-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_userdata_main_userda_uid_d777cf_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userdata',
            name='main_userda_uid_d777cf_idx',
        ),
        migrations.AddIndex(
            model_name='userdata',
            index=models.Index(fields=['uid'], name='main_userda_uid_e1c4c0_idx'),
        ),
    ]
